version: "3.2"
services:
  service-test:
    build:
      context:    .
      dockerfile: ./test.Dockerfile
    env_file:
      - ./.env
    environment:
      - SINATRA_ENV=test
      - RACK_ENV=test
      - DB_HOSTNAME=service-db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    volumes:
      - .:/usr/local/src/service
    depends_on:
      - service-db
  service-db:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
