#%RAML 1.0
title: Service
version: v1
baseUriParameters:
  host:
    description: The host
    enum: [localhost]
baseUri: http://{host}:80/{version}
protocols: [ HTTP, HTTPS ]
mediaType: application/json
types: {
  "Errors":              !include responses/errors.json,
  "HealthCheckResponse": !include responses/health_check.json,
  "PackagesResponse":    !include responses/package.json
}
resourceTypes:
  collection:            !include resource_types/collection.raml
  member:                !include resource_types/member.raml
  member_without_update: !include resource_types/member_without_update.raml
/health_check:
  get:
    responses:
      200:
        description: Service is healthy
        body:
          application/json:
            type: HealthCheckResponse
      500:
        description: Service is unhealthy
        body:
          application/json:
            type: Errors

/packages:
  get:
    responses:
      200:
        description: List indexed R packages
        body:
          application/json:
            type: PackagesResponse
            example: |
              {
                "packages": [
                  {
                    "name": "A3",
                    "version": "1.0.0",
                    "publication_date": "2015-08-16T23:05:52.000Z",
                    "title": "Accurate, Adaptable, and Accessible Error Metrics for Predictive Models",
                    "description": "Supplies tools for tabulating and analyzing the results of predictive models. The methods employed are applicable to virtually any predictive model and make comparisons between different methodologies straightforward.",
                    "authors": [
                      {
                        "name": "Scott Fortmann-Roe",
                        "email": null,
                        "roles": [
                          "aut"
                        ]
                      }
                    ],
                    "maintainers": [
                      {
                        "name": "Scott Fortmann-Roe",
                        "email": "scottfr@berkeley.edu",
                        "roles": [
                          "cre"
                        ]
                      }
                    ]
                  }
                ]
              }

      500:
        description: Service is unhealthy
        body:
          application/json:
            type: Errors
